name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World!"
      - name: Whoami
        run: whoami
      - name: OS version
        run: uname -r
      - name: Print Good bye
        run: echo "Good Bye!"
    
    
