name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World!"
      - name: OS details 
        run: |
          whoami
          uname -r
      - name: Print Good bye
        run: echo "Good Bye!"
    
    
